# Based on the ICU module of the German Medical Informatics Initiative (MII)
# https://www.medizininformatik-initiative.de/Kerndatensatz/Modul_Intensivmedizin/ParametervonBeatmungObservation.html
Airway pressure --at mean expiratory flow on ventilator: []
Airway pressure --at zero inspiratory flow on ventilator:
  # UMCdb
  - Airway pressure --during respiratory pause
  # MIMIC
  - Pressure.plateau Respiratory system airway --on ventilator
  # HiRID
  - Plateau pressure
Airway pressure delta --on ventilator:
  # # UMCdb
  - Airway pressure delta setting Ventilator
Breath rate mechanical --on ventilator:
  # UMCdb
  - Breath rate setting Ventilator
  - Breath rate minimum setting Ventilator
  - Breath rate setting Intermittent mandatory ventilator
  - Breath rate setting Ventilator synchronized intermittent mandatory
  # HiRID
  - Ventilator rate
  # SICdb
  - RespRate
Breath rate spontaneous --on ventilator:
  - Breath rate spontaneous
  # SICdb
  - RespRateSpontanous
Breath rate spontaneous and mechanical --on ventilator:
  # HiRID
  - Respiratory rate
Carbon dioxide [Partial pressure] in Exhaled gas --at end expiration:
  # HiRID
  - End tidal carbon dioxide concentration
  # SICdb
  - etCO2
Dynamic lung compliance:
  # SICdb
  - DynCompliance
Expiratory gas flow Respiratory system airway --on ventilator: []
Expiratory hold time setting Ventilator:
  - Expiration setting [Time] Ventilator
High pressure hold time setting Ventilator: []
Horowitz index in Arterial blood: []
Inspiration/Expiration time Ratio:
  - Inspiration/Expiration setting Ventilator
  # SICdb
  - IERatio
Inspiratory flow setting Ventilator: []
Inspiratory gas flow Respiratory system airway --on ventilator:
Inspiratory time setting Ventilator:
  - Inspiration setting [Time] Ventilator
Inspired minute Volume during Mechanical ventilation: []
Low pressure hold time setting Ventilator: []
Mean pressure Respiratory system airway --on ventilator:
  # HiRID
  - Mean airway pressure
  # SICdb
  - Mean Airway Pressure
  - pMean
Minute volume setting Ventilator: []
Oxygen [Partial pressure] in Exhaled gas: []
Oxygen/Gas total [Pure volume fraction] Inhaled gas:
  - Inhaled oxygen concentration
Oxygen/Total gas setting [Volume Fraction] Ventilator:
  # HiRID
  - Inspired oxygen concentration
  # SICdb
  - FIO2
Oxygen gas flow Oxygen delivery system: []
PEEP Respiratory system --on ventilator:
  - Intrinsic PEEP Respiratory system
  - Positive end expiratory pressure setting Ventilator
  - Total PEEP Respiratory system
  # HiRID
  - Positive end expiratory pressure
  - Positive end expiratory pressure setting
  # SICdb
  - PEEP
Pressure support setting Ventilator:
  # SICdb
  - PressureSupport
Pressure.max Respiratory system airway --on ventilator:
  - Maximum [Pressure] Respiratory system airway opening --during inspiration on ventilator
  # SICdb
  - pPeak
  - PeakInspiratoryPressure
Tidal volume setting Ventilator:
  # HiRID
  - Tidal volume setting
Tidal volume Ventilator --on ventilator: []
Tidal volume.spontaneous --on ventilator: []
Tidal volume.spontaneous+mechanical --on ventilator: []
Ventilation mode Ventilator: []
