# Based on the ICU module of the German Medical Informatics Initiative (MII)
# https://www.medizininformatik-initiative.de/Kerndatensatz/Modul_Intensivmedizin/ParametervonBeatmungObservation.html
# Airway pressure --at mean expiratory flow on ventilator: []
# Airway pressure --at zero inspiratory flow on ventilator: []
Airway pressure delta --on ventilator:
  # UMCdb
  - Airway pressure delta setting Ventilator
Breath rate setting Ventilator:
  # HiRID
  - Ventilator rate
  # SICdb
  - RespRateVentilator
  # UMCdb
  - Breath rate minimum setting Ventilator
  - Breath rate setting Intermittent mandatory ventilator
  - Breath rate setting Ventilator synchronized intermittent mandatory
Breath rate spontaneous --on ventilator:
  # MIMIC
  - Breath rate spontaneous
  # SICdb
  - RespRateSpontanous
Breath rate spontaneous and mechanical --on ventilator:
  # MIMIC
  - Breath rate
  # Both of these refer to non-ventilated data as well as ventilated data
  # and are better suited for the vitals table
  # # HiRID / UMCdb
  # - Respiratory rate
  # # SICdb
  # - RespRate
Carbon dioxide [Partial pressure] in Exhaled gas --at end expiration:
  # HiRID
  - End tidal carbon dioxide concentration
  # SICdb
  - etCO2
Dynamic lung compliance:
  # SICdb
  - DynCompliance
  # UMCdb
  - Dynamic compliance
Expiratory gas flow Respiratory system airway --on ventilator: []
Expiratory hold time setting Ventilator:
  # UMCdb
  - Expiration setting [Time] Ventilator
Expired minute Volume during Mechanical ventilation:
  # UMCdb
  - Expiratory minute volume
High pressure hold time setting Ventilator: []
Horowitz index in Arterial blood: []
Inspiration/Expiration time Ratio:
  # SICdb
  - IERatio
  # UMCdb
  - Inspiration/Expiration setting Ventilator
Inspiratory flow setting Ventilator: []
Inspiratory gas flow Respiratory system airway --on ventilator: []
Inspiratory time setting Ventilator:
  - Inspiration setting [Time] Ventilator
Inspired minute Volume during Mechanical ventilation: []
Low pressure hold time setting Ventilator: []
Mean airway pressure:
  # HiRID
  - Mean inspiratory airway pressure
  # SICdb
  - Mean Airway Pressure
  - pMean
Minute volume setting Ventilator: []
Oxygen [Partial pressure] in Exhaled gas: []
Oxygen/Gas total [Pure volume fraction] Inhaled gas:
  # SICdb
  - Oxyflow O2
  - Optiflow O2
  # UMCdb
  - Inhaled oxygen concentration
Oxygen/Total gas setting [Volume Fraction] Ventilator:
  # HiRID
  - Inspired oxygen concentration
  # MIMIC
  - Inhaled oxygen concentration # refers to FiO2 values according to the original values
  # SICdb
  - FIO2
Oxygen delivery system:
  # MIMIC
  - Oxygen delivery
  # UMCdb
  - Oxygen therapy support
Oxygen gas flow Oxygen delivery system:
  # HiRID
  - Oxygen administration by mask
  - Oxygen administration by nasal cannula
  # SICdb
  - Oxyflow Flow
  - Optiflow Flow
  - O2 Flow
PEEP Respiratory system:
  # HiRID
  - Positive end expiratory pressure
  # UMCdb
  - Intrinsic PEEP Respiratory system
  - PEEP Respiratory system --on ventilator
  - Total PEEP Respiratory system
Positive end expiratory pressure setting Ventilator:
  # HiRID
  - Positive end expiratory pressure setting
  # SICdb
  - PEEP
Pressure support setting Ventilator:
  # SICdb
  - PressureSupport
Pressure.max Respiratory system airway --on ventilator:
  - Maximum [Pressure] Respiratory system airway opening --during inspiration on ventilator
  # MIMIC
  - Pressure max Respiratory system airway --during inspiration
  # SICdb
  - pPeak
  - PeakInspiratoryPressure
  # HiRID
  - Peak inspiratory pressure
Pressure.plateau Respiratory system airway --on ventilator:
  # HiRID
  - Plateau pressure
  # UMCdb
  - Airway pressure --during respiratory pause
Tidal volume.expired:
  # SICdb
  - TV (exp)
  # UMCdb
  - Expiratory tidal volume
  - Tidal volume expired Respiratory system airway --on ventilator
  - Tidal volume expired spontaneous+mechanical Respiratory system airway --on ventilator
Tidal volume.inspired:
  # SICdb
  - TV (insp)
  # UMCdb
  - Tidal volume inspired spontaneous+mechanical Measured --on ventilator
Tidal volume setting Ventilator:
  # HiRID
  - Tidal volume setting
Tidal volume Ventilator --on ventilator: []
Tidal volume.spontaneous --on ventilator: []
Tidal volume.spontaneous+mechanical --on ventilator: []
Ventilation mode Ventilator: []
Ventilator type: []
