person_id_col: person_id
hospital_stay_id_col: hospital_stay_id
icu_stay_id_col: icu_stay_id
icu_stay_seq_num_col: icu_stay_seq_number
global_person_id_col: global_person_id
global_hospital_stay_id_col: global_hospital_stay_id
global_icu_stay_id_col: global_icu_stay_id
mortality_hosp_col: mortality_in_hospital
mortality_icu_col: mortality_in_icu
mortality_after_col: mortality_x_days_after_icu_discharge
pre_icu_length_of_stay_col: pre_icu_length_of_stay
icu_length_of_stay_col: icu_length_of_stay
hospital_length_of_stay_col: hospital_length_of_stay
admission_loc_col: admission_location
admission_type_col: admission_type
admission_diagnosis_col: admission_diagnosis_apache
discharge_loc_col: discharge_location
care_site_col: care_site
unit_type_col: unit_type
specialty_col: specialty
age_col: age
height_col: height_in_cm
weight_col: weight_in_kg
gender_col: gender
ethnicity_col: ethnicity
database_col: source_database
timeseries_time_col: time_relative_to_admission
diagnosis_icd_code_col: diagnosis_icd_code
diagnosis_icd9_code_col: diagnosis_icd9_code
diagnosis_icd10_code_col: diagnosis_icd10_code
diagnosis_icd_version_col: diagnosis_icd_version
diagnosis_start_col: diagnosis_relative_to_admission
diagnosis_priority_col: diagnosis_priority
diagnosis_discharge_col: diagnosis_active_on_discharge
diagnosis_description_col: diagnosis_description
drug_name_col: drug_name
drug_ingredient_col: drug_ingredient
drug_start_col: drug_start_relative_to_admission
drug_end_col: drug_end_relative_to_admission
drug_amount_col: drug_amount
drug_amount_unit_col: drug_amount_unit
drug_rate_col: drug_rate
drug_rate_unit_col: drug_rate_unit
procedure_icd_code_col: procedure_icd_code
procedure_icd_version_col: procedure_icd_version
procedure_start_col: procedure_start_relative_to_admission
procedure_end_col: procedure_end_relative_to_admission
procedure_priority_col: procedure_priority
procedure_discharge_col: procedure_active_on_discharge
procedure_description_col: procedure_description
