reprodICU_files_path: "/data02/projects/reprodicubility/DEVREWRITE/reprodICU_files/"
reprodICU_demo_files_path: "/data02/projects/reprodicubility/DEVREWRITE/reproDEMO/"
OMOP_vocab_path: "/data02/projects/reprodicubility/DEVREWRITE/OMOP_vocabulary/"
eicu_source_path: "/data02/projects/reprodicubility/raw_data/physionet.org/files/eicu-crd/2.0/"
hirid_source_path: "/data02/projects/reprodicubility/raw_data/physionet.org/files/hirid/1.1.1/"
mimic3_source_path: "/data02/projects/reprodicubility/raw_data/physionet.org/files/mimiciii/1.4/"
mimic4_source_path: "/data02/projects/reprodicubility/raw_data/physionet.org/files/mimiciv/2.2/"
nwicu_source_path: "/data02/projects/reprodicubility/raw_data/physionet.org/files/nwicu-northwestern-icu/0.1.0/data/"
sicdb_source_path: "/data02/projects/reprodicubility/raw_data/physionet.org/files/sicdb/1.0.6/"
umcdb_source_path: "/data02/projects/reprodicubility/raw_data/UMCdb/ENCODINGFIX/"

eicu_demo_source_path: "/data02/projects/reprodicubility/raw_data/physionet.org/files/eicu-crd-demo/2.0.1/"
mimic3_demo_source_path: "/data02/projects/reprodicubility/raw_data/physionet.org/files/mimiciii-demo/headerfix/"
mimic4_demo_source_path: "/data02/projects/reprodicubility/raw_data/physionet.org/files/mimic-iv-demo/2.2/"