reprodICU_files_path: "/data02/projects/reprodicubility/DEVREWRITE/reprodICU_files/"
eicu_source_path: "/data02/projects/reprodicubility/raw_data/physionet.org/files/eicu-crd/2.0/"
mimic4_source_path: "/data02/projects/reprodicubility/raw_data/physionet.org/files/mimiciv/2.2/"
mimic3_source_path: "/data02/projects/reprodicubility/raw_data/physionet.org/files/mimiciii/1.4/"
eicu_demo_source_path: "/data02/projects/reprodicubility/raw_data/physionet.org/files/eicu-crd-demo/2.0.1/"
mimic4_demo_source_path: "/data02/projects/reprodicubility/raw_data/physionet.org/files/mimic-iv-demo/2.2/"
mimic3_demo_source_path: "/data02/projects/reprodicubility/raw_data/physionet.org/files/mimiciii-demo/headerfix/"
umcdb_source_path: "/data02/projects/reprodicubility/raw_data/UMCdb/ENCODINGFIX/"
hirid_source_path: "/data02/projects/reprodicubility/raw_data/physionet.org/files/hirid/1.1.1/"
sicdb_source_path: "/data02/projects/reprodicubility/raw_data/physionet.org/files/sicdb/1.0.6/"
