reprodICU_files_path: "/Users/fassbender/Developer/reprodICUbility/reprodICU_OMOP/reprodICU_files/"
reprodICU_demo_files_path: "/Users/fassbender/Developer/reprodICUbility/reprodICU_OMOP/reproDEMO/"
OMOP_vocab_path: "/Users/fassbender/Developer/reprodICUbility/reprodICU_OMOP/OMOP_vocabulary/"
eicu_source_path: "/Users/fassbender/Developer/reprodICUbility/raw_data/physionet.org/files/eicu-crd/2.0/"
hirid_source_path: "/Users/fassbender/Developer/reprodICUbility/raw_data/physionet.org/files/hirid/1.1.1/"
mimic3_source_path: "/Users/fassbender/Developer/reprodICUbility/raw_data/physionet.org/files/mimiciii/1.4/"
mimic4_source_path: "/Users/fassbender/Developer/reprodICUbility/raw_data/physionet.org/files/mimiciv/3.1/"
nwicu_source_path: "/Users/fassbender/Developer/reprodICUbility/raw_data/physionet.org/files/nwicu-northwestern-icu/0.1.0/data/"
umcdb_source_path: "/Users/fassbender/Developer/reprodICUbility/raw_data/UMCdb/ENCODINGFIX/"
sicdb_source_path: "/Users/fassbender/Developer/reprodICUbility/raw_data/physionet.org/files/sicdb/1.0.8/"

eicu_demo_source_path: "/Users/fassbender/Developer/reprodICUbility/raw_data/physionet.org/files/eicu-crd-demo/2.0.1/"
mimic3_demo_source_path: "/Users/fassbender/Developer/reprodICUbility/raw_data/physionet.org/files/mimiciii-demo/headerfix/"
mimic4_demo_source_path: "/Users/fassbender/Developer/reprodICUbility/raw_data/physionet.org/files/mimic-iv-demo/2.2/"